# Generated by Django 2.2.3 on 2019-07-17 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='librarian',
            table='lab_data',
        ),
    ]
